# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160322_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='phpquestion',
            name='all_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='all_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
